{{- $envPrefix := coalesce .Values.generatedEnvPrefix  "" }}
{{- $portName := coalesce .Values.service.portName  "HTTP" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "@@APP_NAME@@.fullname" . }}
  labels:
    {{- include "@@APP_NAME@@.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "@@APP_NAME@@.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "@@APP_NAME@@.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "@@APP_NAME@@.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.service.port }}
          - name: {{ cat $envPrefix "PORT_" $portName | nospace |upper}}
            value: {{ .Values.service.port | quote }}
          {{- else if .Values.service.ports }}
          {{- range $k, $v := .Values.service.ports }}
          {{- if $v.port }}
          - name: {{ cat $envPrefix "PORT_" $v.name |nospace |upper }}
            value: {{ $v.port | quote }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- range $k, $v := .Values.env }}
          - name: {{ $k }}
            value: "{{ $v }}"
          {{- end }}
          ports:
          {{- if .Values.service.port }}
          - containerPort: {{.Values.service.appPort}}
            protocol: TCP
            name: {{ .Values.service.portName | default "http" }}
          {{- else if .Values.service.ports }}
          {{- range $k, $v := .Values.service.ports }}
          {{- if and $v.port $v.name }}
          - containerPort: {{ $v.appPort}}
            protocol: TCP
            name: {{ $v.name }}
          {{- end }}
          {{- end }}
          {{- end }}
          #ports:
          #  - name: http
          #    containerPort: {{.Values.image.containerPort}}
          #    protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
