{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-migration"
  labels:
    {{- include "+( .AppName ).labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-migration"
      labels:
        {{- include "+( .AppName ).joblabels" . | nindent 8 }}
      annotations:
        linkerd.io/inject: disabled
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        {{- if .Values.migrations.image }}
        image: "{{ .Values.migrations.image }}"
        {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- end }}
        {{- if .Values.migrations.command }}
        command: {{ toYaml .Values.migrations.command | nindent 10 }}
        {{- end }}
        {{- if .Values.migrations.args }}
        args: {{ toYaml .Values.migrations.args | nindent 10 }}
        {{- end }}
        env:
        {{- range $k, $v := .Values.env }}
        - name: {{ $k }}
          value: "{{ $v }}"
        {{- end }}
        volumeMounts:
          {{- if .Values.configFiles.enabled }}
          - name: configfiles
            mountPath: {{ .Values.configFiles.mountPath }}
            readOnly: true
          {{- end }}
      volumes:
      {{- if .Values.configFiles.enabled }}
      - name: configfiles
        configMap:
          name: {{ include "+( .AppName ).fullname" . }}
      {{- end }}
{{- end }}
